# Generated by Django 4.2.6 on 2023-10-28 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('fio', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Mailling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_to_send', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начало отправки')),
                ('stop_to_send', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начало отправки')),
                ('periodicity', models.CharField(choices=[('DAILY', 'Каждый день'), ('WEEKLY', 'Каждую неделю'), ('MONTHLY', 'Каждый месяц')], max_length=50, verbose_name='Периодичность')),
                ('status', models.BooleanField(default=False, max_length=20, verbose_name='Пуск рассылки')),
                ('client', models.ManyToManyField(to='mailling.client', verbose_name='Кому')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling.message', verbose_name='Сообщение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Время последней попытки')),
                ('status_try', models.CharField(choices=[('OK', 'Успешно'), ('FAILED', 'Ошибка')], default='Успешно', max_length=50, verbose_name='Статус попытки')),
                ('answer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ответ сервера')),
                ('client', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email клиента')),
                ('mailling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailling.mailling', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
