# Generated by Django 4.2.6 on 2023-10-17 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailling',
            name='time_to_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начало отправки'),
        ),
    ]
