# Generated by Django 4.2.6 on 2023-10-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0002_alter_mailling_time_to_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='error_msg',
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_try',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время последней попытки'),
        ),
    ]
