# Generated by Django 4.2.6 on 2023-10-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailling', '0003_remove_logs_date_end_remove_logs_error_msg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status_try',
            field=models.CharField(choices=[('OK', 'Успешно'), ('FAILED', 'Ошибка')], default='Успешно', max_length=50, verbose_name='Статус попытки'),
        ),
    ]
